[global]
# allow-missing-formatter = true
excludes = [
  "LICENSE",
  "**/node_modules/**",
  "**/target/**",
  "**/.git/**",
  "**/dist/**",
  "**/build/**",
  "**/review/**",
  "**/archive/**",
  "*.lock",
  "Assets/**",
  "*.diff",
  "*.patch",
]

#╔════════════════════════════════╗
#║ Nix                            ║
#╚════════════════════════════════╝

[formatter.alejandra]
command = "sh"
includes = ["*.nix"]
priority = 1
options = [
  "-c",
  "command -v alejandra >/dev/null 2>&1 && alejandra \"$@\" || true",
  "--",
]

#╔════════════════════════════════╗
#║ Rust                           ║
#╚════════════════════════════════╝

# [formatter.rust]
# command = "sh"
# includes = ["*.rs"]
# options = ["-c", "sh \"${TREEFMT_ROOT}/scripts/fmt-rust.sh\" \"$@\"", "--"]

[formatter.leptosfmt]
command = "leptosfmt"
includes = ["*.rs"]
priority = 1

[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]
priority = 2

#╔════════════════════════════════╗
#║ Shellscript                    ║
#╚════════════════════════════════╝

[formatter.shellcheck]
includes = [
  "*.sh",
  ".env*",
  ".shellcheckrc",
  "*.bash",
  ".bash*",
  "Bin/shellscript/**",
]
excludes = ["*.md", "*.ps1", "*.psm1", "*.txt", "*.log"]
command = "shellcheck"
priority = 1

[formatter.shfmt]
includes = [
  "*.bash*",
  "*.env*",
  "*.gitignore",
  "*.ignore",
  "*.sh",
  "*.shellcheckrc",
]
excludes = ["*.md", "*.ps1", "*.psm1", "*.txt", "*.log", "*.rs"]
command = "shfmt"
options = [
  "--apply-ignore",
  "--binary-next-line",
  "--space-redirects",
  "--case-indent",
  "--indent",
  "2",
  "--posix",
  "--write",
]
priority = 2

#╔════════════════════════════════╗
#║ Toml                           ║
#╚════════════════════════════════╝

[formatter.toml]
includes = ["*.toml", "rust-analyzer.toml", "rustfmt.toml"]
command = "taplo"
options = ["format"]

#╔════════════════════════════════╗
#║ Web                            ║
#╚════════════════════════════════╝

[formatter.deno]
command = "deno"
excludes = []
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsonc",
  "*.jsx",
  "*.less",
  "*.markdown",
  "*.md",
  "*.sass",
  "*.scss",
  "*.ts",
  "*.tsx",
  "*.yaml",
  "*.yml",
]
options = ["fmt"]

#╔════════════════════════════════╗
#║ Yaml                           ║
#╚════════════════════════════════╝

[formatter.actionlint]
command = "actionlint"
excludes = []
includes = [".github/workflows/*.yml", ".github/workflows/*.yaml"]
options = []
priority = 2
